version: '3'
services:
  "webtodo":
    build: "./webtodo"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./webtodo/src:/webtodo/src"
    depends_on: 
      - db
      - db2
      - redis
  db:
    build: ./db
    ports: 
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB"
  db2:
    build: ./db2
    ports: 
      - "3307:3307"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB2"
  redis:
    image: "redis"
    ports: 
      - "6379:6379"